services:
  ums-frontend:
    build: ./frontend
    networks:
      - ums-user-facing
  ums-backend:
    build: ./backend
    networks:
      - ums-user-facing
      - ums-back-office
    environment:
      UMS_DB_NAME: ums 
      UMS_DB_USERNAME: dev 
      UMS_DB_PASSWORD: /run/secrets/db_password
      UMS_DB_IP: db
    depends_on:
      - db
    restart: always
    secrets:
      - db_password
  db:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: ums
      MARIADB_USER: dev
      MARIADB_PASSWORD: /run/secrets/db_password
      MARIADB_ROOT_PASSWORD: /run/secrets/db_root_password
    networks:
      - ums-back-office
    volumes:
      - db-data:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
  proxy:
    image: nginx:1.21
    ports:
      - "8080:80"
    networks:
      - ums-user-facing
    depends_on:
      - ums-frontend
      - ums-backend
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
networks:
  ums-user-facing:
  ums-back-office:
volumes:
  db-data:
secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
