services:
  ums-frontend:
    build: ./frontend
    ports:
      - "8080:80"
  ums-db:
    image: mariadb:11
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: dev
      MARIADB_PASSWORD: devpass 
      MARIADB_ROOT_PASSWORD: mypass
