services:
  ums-frontend:
    build: ./frontend
    networks:
      - ums-user-facing
  ums-backend:
    build: ./backend
    networks:
      - ums-user-facing
      - ums-back-office
    depends_on:
      - ums-db
  ums-db:
    image: mariadb:11
    environment:
      MARIADB_USER: dev
      MARIADB_PASSWORD: devpass 
      MARIADB_ROOT_PASSWORD: mypass
    networks:
      - ums-back-office
  ums-proxy:
    image: nginx:1.21
    ports:
      - "8080:80"
    networks:
      - ums-user-facing
    depends_on:
      - ums-frontend
      - ums-backend
networks:
  ums-user-facing:
  ums-back-office:
